conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('chat/', include('conversation.urls')),
    path('', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

conversation/urls.py
from django.urls import path
from .views import ConversationView, choice_for_delete, DeleteMessageView, SendFileView, DeleteChatView, GroupMessageView
from .views import CreateGroupView

app_name = 'conversation'
urlpatterns = [
    path('chat/<int:pk>/', ConversationView.as_view(), name='chat'),
    path('send-file/<int:pk>/', SendFileView.as_view(), name='send-file'),
    path('delete-chat/<int:pk>/', DeleteChatView.as_view(), name='delete-chat'),
    path('choice-for-delete/<int:pk>/', choice_for_delete, name='choice-for-delete'),
    path('delete-message/<int:pk>/', DeleteMessageView.as_view(), name='delete-message'),

    path('group/<int:pk>/', GroupMessageView.as_view(), name='group'),
    path('create-group/', CreateGroupView.as_view(), name='create-group'),
]

home/urls.py
from django.urls import path
from .views import UserListView


app_name = 'home'
urlpatterns = [
    path('', UserListView.as_view(), name='users-list'),
]

users/urls.py
from django.urls import path

from .views import MyProfileView, ProfileView, Registration, Login, Logout, get_choice, EditProfile


app_name = 'users'
urlpatterns = [
    path('', get_choice, name='users'),
    path('profile/', MyProfileView.as_view(), name='my-profile'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('edit-profile/<int:pk>/', EditProfile.as_view(), name='edit-profile'),

    path('register/', Registration.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class Users(AbstractUser):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    profile_picture = models.ImageField(upload_to='pictures/profile_picture/', blank=True, default='default/profile_picture/user.png')
    status_message = models.TextField(blank=True)

    class Meta:
        db_table = 'users'

    def __str__(self):
        return f"user: {self.username}"

users/forms.py
from django import forms
from django.forms import CharField, ModelForm, PasswordInput
from .models import Users


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Users
        fields = ['username', 'status_message', 'password', 'profile_picture', 'first_name', 'last_name']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class EditProfileForm(ModelForm):
    password = CharField(widget=PasswordInput)

    class Meta:
        model = Users
        fields = ['username', 'status_message', 'password', 'profile_picture', 'first_name', 'last_name']

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views import View
from .forms import RegistrationForm, EditProfileForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

from .models import Users
from conversation.models import Groups
# Create your views here.


def get_choice(request):
    return render(request, 'choice_enter.html')


class MyProfileView(View):
    def get(self, request):
        user = Users.objects.get(pk=request.user.pk)
        groups = Groups.objects.filter(Q(owner=user))
        print(groups)
        context = {
            'user': user,
            'groups': groups
        }
        return render(request, 'my_profile.html', context)


class ProfileView(View):
    def get(self, request, pk):
        user = Users.objects.get(pk=pk)
        groups = Groups.objects.filter(Q(owner=user))
        context = {
            'user': user,
            'groups': groups
        }
        return render(request, 'profile.html', context)


class Registration(View):
    def get(self, request):
        registration_form = RegistrationForm()
        context = {
            'registration_form': registration_form
        }
        return render(request, 'registration.html', context=context)

    def post(self, request):
        registration_form = RegistrationForm(data=request.POST, files=request.FILES)
        if registration_form.is_valid():
            print(f"{request.user} is valid")
            registration_form.save()
            return redirect('users:login')
        else:
            context = {
                'registration_form': registration_form
            }
            print(f'user -{request}  invalid')
            return render(request, 'registration.html', context=context)


class Login(View):
    def get(self, request):
        login_form = AuthenticationForm()
        context = {
            'login_form': login_form
        }
        return render(request, 'login.html', context=context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            account = login_form.get_user()
            login(request, account)
            return redirect('home:users-list')

        else:
            context = {
                'login_form': login_form
            }
            return render(request, 'login.html', context=context)


class Logout(View, LoginRequiredMixin):
    def get(self, request):
        logout(request)
        return redirect('users:users')


class EditProfile(View):
    def get(self, request, pk):
        profile = Users.objects.get(pk=pk)
        edit_profile_form = EditProfileForm(instance=profile)
        context = {
            'edit_profile_form': edit_profile_form
        }
        return render(request, 'edit_profile.html', context=context)

    def post(self, request, pk):
        profile = Users.objects.get(pk=pk)
        edit_profile_form = EditProfileForm(request.POST, instance=profile)
        if edit_profile_form.is_valid():
            user = edit_profile_form.save(commit=False)
            password = edit_profile_form.cleaned_data.get('password')
            user.set_password(password)
            user.save()
            return redirect('profile')
        else:
            context = {
                'edit_profile_form': edit_profile_form
            }
            return render(request, 'edit_profile.html', context=context)

users/templates/choice_enter.html
<title>Enter</title>
<center>
    <h1>Choice</h1>
    <a href="{% url 'users:register' %}"><button>Register</button></a>
    <a href="{% url 'users:login' %}"><button>Login</button></a>
</center>

users/templates/edit_profile.html
<title>Edit Profile</title>
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/for_edit_profile.css' %}">
</head>
<center>
    <h1>Edit Profile</h1>
    <form method="post">{% csrf_token %}
        {{ edit_profile_form.as_p }}
    <button type="submit">Edit</button>
</form>
</center>

users/templates/login.html
<title>Login</title>
<center>
    <h1>Login</h1>
    <form method="post">{% csrf_token %}
            {{ login_form.as_p }}
            <button type="submit">Login</button>
        </form>
</center>

users/templates/my_profile.html
<title>MyProfile</title>

<center>
    <div>
        <img src="{{ user.profile_picture.url}}" width="200px">
        <h2>{{ user.username }}</h2>
        <h3>{{ user.first_name }} {{ user.last_name }}</h3>
        {{ user.status_message }}<br><br><br><br>
    </div>

        <a href="{% url 'users:edit-profile' user.pk %}"><button>Edit Profile</button></a>
        <a href="{% url 'conversation:create-group' %}"><button>Create Group</button></a>
        <a href="{% url 'users:logout' %}"><button>Logout</button></a><br><br>

    {% if groups %}
        <h1>Groups</h1>
        {% for group in groups %}
            <a href="{% url 'conversation:group' group.pk %}"><img src="{{ group.group_picture.url }}" width="200px"></a><br>
            <h3>{{ group.name }}</h3>
        {% endfor %}
    {% endif %}

    <a href="{% url 'home:users-list' %}"><button>Home</button></a>
</center>

users/templates/profile.html
<title>Profile</title>

<center>
    <div>
        <img src="{{ user.profile_picture.url}}" width="200px">
        <h2>{{ user.username }}</h2>
        <h3>{{ user.first_name }} {{ user.last_name }}</h3>
        {{ user.status_message }}<br><br><br><br>
    </div>


    {% if groups %}
        <h1>Groups</h1>
        {% for group in groups %}
            <a href=""><img src="{{ group.group_picture.url }}" width="200px"></a><br>
            <h3>{{ group.name }}</h3>
        {% endfor %}
    {% endif %}

    <a href="{% url 'home:users-list' %}"><button>Home</button></a>
    <a href="{% url 'conversation:delete-chat' user.pk %}"><button>Clear Chat</button></a>
</center>

users/templates/registration.html
    <title>Registration</title>
<center>
    <h2>Registration</h2>
    <form method="post">{% csrf_token %}
        {{ registration_form.as_p }}
        <button type="submit">Register</button>
    </form>
</center>