conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('chat/', include('conversation.urls')),
    path('', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

conversation/urls.py
from django.urls import path
from .views import ConversationView, choice_for_delete, DeleteMessageView, SendFileView, DeleteChatView, GroupMessageView
from .views import CreateGroupView

app_name = 'conversation'
urlpatterns = [
    path('chat/<int:pk>/', ConversationView.as_view(), name='chat'),
    path('send-file/<int:pk>/', SendFileView.as_view(), name='send-file'),
    path('delete-chat/<int:pk>/', DeleteChatView.as_view(), name='delete-chat'),
    path('choice-for-delete/<int:pk>/', choice_for_delete, name='choice-for-delete'),
    path('delete-message/<int:pk>/', DeleteMessageView.as_view(), name='delete-message'),

    path('group/<int:pk>/', GroupMessageView.as_view(), name='group'),
    path('create-group/', CreateGroupView.as_view(), name='create-group'),
]

home/urls.py
from django.urls import path
from .views import UserListView


app_name = 'home'
urlpatterns = [
    path('', UserListView.as_view(), name='users-list'),
]

users/urls.py
from django.urls import path

from .views import MyProfileView, ProfileView, Registration, Login, Logout, get_choice, EditProfile


app_name = 'users'
urlpatterns = [
    path('', get_choice, name='users'),
    path('profile/', MyProfileView.as_view(), name='my-profile'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('edit-profile/<int:pk>/', EditProfile.as_view(), name='edit-profile'),

    path('register/', Registration.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from users.models import Users


class UserSearchForm(forms.Form):
    query = forms.CharField(max_length=150, label="Search", required=False)

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from users.models import Users
from conversation.models import PrivateMessage
# Create your views here.


class UserListView(View):
    def get(self, request):
        users = Users.objects.exclude(pk=request.user.id)
        my_profile = get_object_or_404(Users, pk=request.user.id)
        context = {
            'my_profile': my_profile,
            'users': users,
        }
        return render(request, 'home.html', context=context)

home/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
</head>
<style>
    div.my-profile {
        display: flex;
        flex-direction: column;
        border-bottom: 1px solid #ddd;
    }
</style>
    <header>
        {% if messages %}
            {% for message in messages %}
                {{ message }}<br><br>
            {% endfor %}
        {% endif %}
        <div class="my-profile">
            <a href="{% url 'users:my-profile' %}"><img src="{{ my_profile.profile_picture.url }}" width="90px"></a>
            {{ user.first_name }} {{ user.last_name }}<br><br>
        </div>

        {% if users.exists %}
            {% for user in users %}
                <a href="{% url 'conversation:chat' user.pk %}"><img src="{{ user.profile_picture.url }}" width="80px"></a>
                {{ user.first_name }} {{ user.last_name }}<br><br>
            {% endfor %}
        {% endif %}
    </header>
</html>